server:
 port: 8090

spring:
 r2dbc:
  url: r2dbc:mysql://localhost:3306/simple_notice_board?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  username: root
  password: 1234

logging:
 level:
  org:
   springframework:
    r2dbc: DEBUG
